"use strict";

//HTML용 언어팩
//lang ko, en 둘중 하나
$.htmlDictionary = {};
$.attrDictionary = {};
$.htmlDictionary.ko = {
  0: '일정창 보기',
  1: '장소창 보기',
  2: '사용이 불편하신가요?',
  3: '추천호텔',
  4: '추천장소',
  5: '이용방법',
  6: '장소등록',
  7: '추천일정',
  8: '피드백',
  9: '일정생성',
  10: '하단의 화살표 버튼을 눌러 페이지를 이동하세요. 자세한 이용방법을 영상으로 보시려면 왼쪽 상단에 YouTube영상 버튼을 눌러주세요.',
  11: 'YouTube영상 보러가기 (채널 : 방구석tv)',
  12: '호텔',
  13: '장소',
  14: '장소명을 검색하세요.',
  15: '검색어는 두 글자 이상 입력해주세요.',
  16: '검색 결과가 없습니다.<br>찾으시는 장소를 좌측 장소등록버튼으로 등록 해주세요.',
  17: '일정작성',
  18: '여행시간 상세설정',
  19: '(총',
  20: '시간',
  21: '분)',
  22: '일자별 시작시간과 종료시간을 설정하세요.',
  23: '기본값은 오전10시부터 오후10시까지 12시간입니다.',
  24: '선택목록',
  25: '호텔전체삭제',
  26: '장소전체삭제',
  27: '가고 싶은 장소들을 검색하여 추가해주세요.',
  28: '설정하신 일자별 여행시간 내에서 ',
  29: '하루 평균 최대 8개의 장소까지 선택 가능합니다.',
  30: '저희 서비스에 대해서 불편한 점, 개선할 점 등을 적어주세요.',
  31: '항상 유저분들의 귀중한 피드백을 기다리고 있습니다.',
  32: '이름(생략가능, 최대 20자)',
  33: '이메일(생략가능, 최대 100자)',
  34: '내용(최대 1000자)',
  35: '피드백 보내기',
  36: '장 소 등 록',
  37: '검색해도 나오지 않는 장소를 이곳에서 등록 후 다시 검색해보세요.<br>추가하실 장소이름과 설명사항을 적어주세요.',
  38: '장소이름(최대 50자)',
  39: '설명사항(최대 200자, 생략 가능)',
  40: '추가하실 장소의 유형을 선택해주세요.',
  41: '장소',
  42: '식당',
  43: '호텔',
  44: '검색',
  45: '검 색 결 과',
  46: '총',
  47: '건의 결과(최대 20개)',
  48: '검색결과창 닫기',
  49: '닫 기',
  50: '일정저장',
  51: '이메일로 모바일에서 이용이 가능한 일정 페이지를 전송합니다.<br>전송을 하지 않아도 일정을 엑셀파일로 다운로드가 가능합니다.<br>단, 전송을 하지 않으면 만들어진 일정이 저장되지 않으니 주의하세요.',
  52: '여행이름',
  53: '이메일',
  54: '이메일로 일정 전송하기',
  55: '엑셀파일 다운로드',
  56: '이전화면으로 돌아가기',
  57: '개의 장소',
  58: '일정',
  59: '전체일정',
  60: '일 여행',
  61: '+ 버튼을 누르면 포함되지 않은 장소에 추가됩니다.',
  62: '수정저장',
  63: '수정취소',
  64: '엑셀다운',
  65: '일정전송',
  66: '일주일간 보지 않기',
  67: '가이드',
  68: '나만의 여행일정 만드는 법',
  69: 'MYRO 일정수정 사용법',
  70: '현재 창을 이메일 전송 없이 닫으시면 일정이<br>저장되지 않습니다. 창을 닫으시겠습니까?',
  71: '일정수정페이지 가이드',
  72: '호 텔',
  73: '장 소',
  74: '앱 연동 키'
};
$.htmlDictionary.en = {
  0: 'plan tab',
  1: 'places tab',
  2: 'have problems?',
  3: 'recommend hotel',
  4: 'recommend place',
  5: 'guide',
  6: 'add place',
  7: 'recommend course',
  8: 'feedback',
  9: 'make plan',
  10: 'use the arrow buttons below to move page. You can watch how to use the service on youtube with the youtube button on the left.',
  11: 'Go to youtube (channel : 방구석tv)',
  12: 'hotel',
  13: 'place',
  14: 'search with keyword',
  15: 'the keyword should be longer than 2 letters',
  16: 'there is no result<br>please use the "add place" button on the left and register the place',
  17: 'set your wish',
  18: 'daily active time',
  19: '(total ',
  20: 'H ',
  21: 'M)',
  22: 'set the start time and end time by day',
  23: 'default is 10:00 to 22:00',
  24: 'select list',
  25: 'DELETE ALL',
  26: 'DELETE ALL',
  27: 'search and grab the places you want to visit',
  28: 'you can grab for average maximum 8 places per day',
  29: 'from your travel days',
  30: 'please let us know about your problems using our service',
  31: 'we are always eager to listen our user\'s feedback',
  32: 'name (optional, maximum 20 letters)',
  33: 'e-mail (optional, maximum 100 letters)',
  34: 'tell us your story (maximum 1000 letters)',
  35: 'send feedback',
  36: 'add place',
  37: 'register the place that you can\'t find, then search it again',
  38: 'place name (maximum 50 letters)',
  39: 'description (optional, maximum 200 letters)',
  40: 'please choose the type of the place',
  41: 'spot',
  42: 'restaurant',
  43: 'hotel',
  44: 'search',
  45: 'search result',
  46: 'total ',
  47: ' resutls(maximum 20)',
  48: 'close the result list',
  49: 'close',
  50: 'save plan',
  51: 'you can send your mobile plan page to your email or download by excel file',
  52: 'travel name',
  53: 'e-mail',
  54: 'send e-mail',
  55: 'download excel file',
  56: 'go back',
  57: ' places',
  58: 'schedule',
  59: 'whole plan',
  60: ' day plan',
  61: 'use + button to add place into \'not included\' list',
  62: 'save modification',
  63: 'cancel modification',
  64: 'excel download',
  65: 'save plan',
  66: 'don\'t show for 1 week',
  67: 'guide',
  68: 'how to make your own plan',
  69: 'how to modify',
  70: 'If you close this window without saving,<br> the plan will be deleted. <br>Are you sure to close this window?',
  71: 'plan modify guide',
  72: 'HOTEL',
  73: 'PLACE',
  74: 'copy key'
};
$.attrDictionary.ko = {
  0: '이용자들이 가장 많이 선택한 호텔들을 표시합니다.',
  1: '이용자들이 가장 많이 선택한 장소들을 표시합니다.',
  2: '이용방법',
  3: '장소등록',
  4: '추천코스목록',
  5: '피드백 보내기',
  6: '이동수단 : 대중교통',
  7: '이동수단 : 자동차',
  8: '일정생성',
  9: '각각의 장소를 일일이 선택하거나 전체선택으로 전체 여행시간 내에 방문 가능한 모든 장소를 선택하세요',
  10: '검색어를 입력하세요.',
  11: '보내주신 피드백은 운영자가 확인 후 최대한 신속하게 답변 드리겠습니다.',
  12: '구글지도에서 검색되는 결과만 표시됩니다. 도시 중심에서 반경 50km 이내의 결과만 표시됩니다.',
  13: '장소를 검색하여 일정에 추가',
  14: '장소를 검색하여 일정에 추가하세요.',
  15: '이용방법',
  16: '장소이동과 시간 조정 수정사항을 저장합니다. 저장 후에는 취소할 수 없습니다.',
  17: '초기 일정 혹은 수정저장 후 일정을 기준으로 변경을 취소합니다.',
  18: '엑셀파일을 다운로드합니다.',
  19: '현재 일정을 확정하여 저장합니다.',
  20: '여행 이름',
  21: '이메일 주소',
  22: '앱에서 연동가능한 키를 복사합니다.'
};
$.attrDictionary.en = {
  0: 'you can see the hotels ranked by user\'s choice',
  1: 'you can see the places ranked by user\'s choice',
  2: 'guide',
  3: 'add place',
  4: 'recommend course list',
  5: 'send feedback',
  6: 'MODE : TRANSIT',
  7: 'MODE : DRIVING',
  8: 'make plan',
  9: 'you can select each place or use \'select all\' button to select all the places in your travel time capacity',
  10: 'insert keyword',
  11: 'your feedback will be reviewd and replied as soon as possible',
  12: 'the result is only based on the result of google maps, and only in 25kms from the center of the city',
  13: 'find place and add',
  14: 'find place and add',
  15: 'guide',
  16: 'reflect your modification. after reflect, you can\'t cancel it',
  17: 'restore your plan to before your modification',
  18: 'download by excel',
  19: 'set your plan and save',
  20: 'travel name',
  21: 'email address',
  22: 'copy key for mobile app'
};
$(document).ready(function () {
  $('[data-langNum]').each(function () {
    var $this = $(this);
    $this.html($.htmlDictionary[lang][$this.data('langnum')]);
  });
  $('[data-attrNum]').each(function () {
    var $this = $(this);
    var attrType = 'data-tooltip';

    if ($this.data('attrtype')) {
      attrType = $this.data('attrtype');
    }

    $this.attr(attrType, $.attrDictionary[lang][$this.data('attrnum')]);
  });
});